# Generated by Django 5.2.2 on 2025-06-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('EUA', 'Estados Unidos'), ('BR', 'Brasil'), ('FR', 'França'), ('JP', 'Japão')], max_length=100, null=True)),
            ],
        ),
    ]
